name: Build and push to registry

on:
  release:
    types: [ released ]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push tag
        if: ${{ github.ref_type == 'tag' }}
        uses: docker/build-push-action@v3
        with:
          push: true
          tags:
            nitrotol/devops-gitpod:${{ github.ref_name }}
            nitrotol/devops-gitpod:latest
      - name: Set env for tag
        if: ${{ github.ref_type != 'tag' }}
        run: echo "NIGHTLY_TAG=$(date +%m-%Y)" >> $GITHUB_ENV
      - name: Build and push tag
        if: ${{ github.ref_type != 'tag' }}
        uses: docker/build-push-action@v3
        with:
          push: true
          tags:
            nitrotol/devops-gitpod:nightly-latest
            nitrotol/devops-gitpod:nightly-${{ env.NIGHTLY_TAG }}
